# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_zencoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Duration (ms)'),
        ),
        migrations.AlterField(
            model_name='format',
            name='extra_info',
            field=models.TextField(blank=True, verbose_name='Zencoder information (JSON)'),
        ),
        migrations.AlterField(
            model_name='format',
            name='format',
            field=models.CharField(choices=[('mp4-high', 'mp4-high'), ('mp4-low', 'mp4-low')], max_length=255),
        ),
        migrations.AlterField(
            model_name='format',
            name='height',
            field=models.PositiveIntegerField(null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='format',
            name='width',
            field=models.PositiveIntegerField(null=True, verbose_name='Width'),
        ),
    ]
